//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface DOCKRecentsModel : NSObject
{
    id _icon;
    NSString *_displayName;
    id _item;
}

@property(readonly, nonatomic) id icon; // @synthesize icon=_icon;
@property(readonly, nonatomic) id item; // @synthesize item=_item;
@property(readonly, nonatomic) NSString *displayName; // @synthesize displayName=_displayName;
- (void).cxx_destruct;
- (long long)compare:(id)arg1;
- (id)initWithSharedFileListItem:(id)arg1;

@end

