//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSCache, NSMutableSet;

@interface DOCKRecentsCache : NSObject
{
    NSCache *_cache;
    NSMutableSet *_cacheItems;
    unsigned long long _itemCost;
}

@property(readonly, nonatomic) unsigned long long itemCost; // @synthesize itemCost=_itemCost;
- (void).cxx_destruct;
- (void)setCurrentItems:(id)arg1;
- (void)setItem:(id)arg1 forID:(unsigned int)arg2;
- (id)itemForID:(unsigned int)arg1;
- (id)initWithCost:(unsigned long long)arg1;

@end

