//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DOCKEvent.h"

@interface DOCKAutoHideEnabledEvent : DOCKEvent
{
    _Bool _setRect;
}

- (void)perform:(CDStruct_95d471ab *)arg1;
- (id)initWithSetRect:(_Bool)arg1;

@end

