//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "DOCKGestureHandler.h"

@class NSString;

@interface DOCKGestureDefaultHandler : NSObject <DOCKGestureHandler>
{
}

- (_Bool)isFluidGesturing;
- (void)fluidGestureEnd:(id)arg1;
- (void)fluidGestureProgress:(id)arg1;
- (_Bool)fluidGestureStart:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

