//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class DPRemoteConnection;

@protocol DPDesktopWindow <NSObject>
@property(nonatomic) _Bool blurredForExpose;
@property(nonatomic) BOOL darkened;
@property(readonly, nonatomic) BOOL isReady;
@property(readonly, nonatomic) unsigned int wid;
- (void)removeRemoteConnection:(DPRemoteConnection *)arg1;
- (unsigned int)addRemoteConnection:(DPRemoteConnection *)arg1;
@end

