//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class ECBezelIconListLayer;

@protocol ECBezelIconListLayerActions <NSObject>
- (unsigned int)windowForBezelIconListLayer:(ECBezelIconListLayer *)arg1;
- (struct CGRect)bezelIconListLayer:(ECBezelIconListLayer *)arg1 convertRectToGlobal:(struct CGRect)arg2;
- (_Bool)bezeIconListLayer:(ECBezelIconListLayer *)arg1 itemDroppedAtIndex:(unsigned long long)arg2 forDrag:(struct OpaqueCoreDrag *)arg3;
- (void)bezeIconListLayer:(ECBezelIconListLayer *)arg1 itemAtIndexSelected:(unsigned long long)arg2 forDrag:(struct OpaqueCoreDrag *)arg3;
- (void)bezeIconListLayer:(ECBezelIconListLayer *)arg1 itemAtIndexSelected:(unsigned long long)arg2;
- (void)bezeIconListLayer:(ECBezelIconListLayer *)arg1 itemAtIndexClicked:(unsigned long long)arg2;
@end

