//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "LPAppTreeNode.h"

@class NSMutableDictionary;

@interface LPAppTree : LPAppTreeNode
{
    NSMutableDictionary *_nodesByBundleIdentifier;
}

- (void).cxx_destruct;
- (id)treeDescription;
- (id)nodesForBundleIdentifier:(id)arg1;
- (void)iterateAllAppsAtPath:(id)arg1 matching:(CDUnknownBlockType)arg2;
- (id)subNodeAtPath:(id)arg1;
- (void)removeApps:(id)arg1;
- (void)mergeTree:(id)arg1;
- (id)splitOutTreeAtPath:(id)arg1;
- (void)removeApp:(id)arg1;
- (void)addApps:(id)arg1;
- (id)addApp:(id)arg1;
- (void)addAppsFromGroup:(id)arg1;
- (id)init;

@end

