//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSException.h"

@class NSString;

@interface LPDatabaseException : NSException
{
    NSString *_method;
    long long _line;
    long long _dbError;
    NSString *_dbErrorStr;
}

@property(readonly) NSString *dbErrorStr; // @synthesize dbErrorStr=_dbErrorStr;
@property(readonly) long long dbError; // @synthesize dbError=_dbError;
@property(readonly) long long line; // @synthesize line=_line;
@property(readonly) NSString *method; // @synthesize method=_method;
- (void).cxx_destruct;
- (id)description;
- (id)initExceptionInMethod:(const char *)arg1 lineNumber:(long long)arg2 database:(struct sqlite3 *)arg3 ret:(int)arg4;

@end

