//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SpringboardDragCacheItem : NSObject
{
    struct FSRef _ref;
    BOOL _accepts;
    struct OpaqueCoreDrag *_drag;
}

@property(nonatomic) BOOL accepts; // @synthesize accepts=_accepts;
@property(readonly, nonatomic) struct OpaqueCoreDrag *drag; // @synthesize drag=_drag;
@property(readonly, nonatomic) struct FSRef fsref; // @synthesize fsref=_ref;
- (id)initWithRunnable:(id)arg1 drag:(struct OpaqueCoreDrag *)arg2 forceAcceptance:(BOOL)arg3;

@end

