//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface WVSpaceSwitcherSpace : NSObject
{
    struct __CFArray *_windows;
}

- (void)setTransform:(struct CGAffineTransform)arg1 withClipRegion:(struct CGSRegionObject *)arg2;
- (void)addWindow:(unsigned int)arg1;
- (id)description;
- (void)dealloc;
- (id)init;

@end

