//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface _LPLayoutRule : NSObject
{
    NSString *_stringToMatch;
    BOOL _matchesToBundleIdentifier;
}

+ (id)rule:(id)arg1;
@property(readonly, nonatomic) BOOL matchesToBundleIdentifier; // @synthesize matchesToBundleIdentifier=_matchesToBundleIdentifier;
@property(readonly, nonatomic) NSString *stringToMatch; // @synthesize stringToMatch=_stringToMatch;
- (void).cxx_destruct;
- (BOOL)match:(id)arg1;
- (BOOL)matchItem:(id)arg1;
- (id)initWithRule:(id)arg1;

@end

