//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, WVDisplay;

@interface _WVGestureDisplayInfo : NSObject
{
    WVDisplay *_display;
    NSArray *_windowInfos;
}

@property(retain, nonatomic) NSArray *windowInfos; // @synthesize windowInfos=_windowInfos;
@property(retain, nonatomic) WVDisplay *display; // @synthesize display=_display;
- (void).cxx_destruct;
- (id)initWithDisplay:(id)arg1 windowInfos:(id)arg2;

@end

