//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface DBBackgroundWindows : NSObject
{
    unsigned int _cid;
    unsigned int *_backgroundWindows;
    unsigned int _backgroundWindowCount;
    struct {
        struct OpaqueCoreDragHandler *_field1;
        struct OpaqueCoreDragHandler *_field2;
    } *_handlers;
}

- (void)order:(int)arg1;
- (void)setAlpha:(float)arg1;
- (void)setSpace:(id)arg1;
@property(readonly, nonatomic) unsigned int mainWindow;
- (void)dealloc;
- (id)initWithConnection:(unsigned int)arg1 trackingHandler:(CDUnknownFunctionPointerType)arg2 receiveHandler:(CDUnknownFunctionPointerType)arg3;

@end

