//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DOCKStackExpandedItemLayer.h"

@class CALayer, ECRoundBackdropLayer;

@interface DOCKStackFanItemLayer : DOCKStackExpandedItemLayer
{
    CALayer *_shadowLayer;
    ECRoundBackdropLayer *_backdropLayer;
}

@property(readonly, nonatomic) ECRoundBackdropLayer *backdropLayer; // @synthesize backdropLayer=_backdropLayer;
@property(retain, nonatomic) CALayer *shadowLayer; // @synthesize shadowLayer=_shadowLayer;
- (void).cxx_destruct;
- (id)hitTest:(struct CGPoint)arg1;
- (void)layoutSublayers;
- (void)setTinted:(BOOL)arg1;
- (void)setText:(id)arg1;
- (void)setScaleFactor:(float)arg1;
- (void)darkenForProgress:(BOOL)arg1;
- (CDStruct_caf9bca6)previewRect;
@property(readonly, nonatomic) struct CGRect backdropLayerFrame;
@property(readonly, nonatomic) struct CGRect imageLayerFrame;
- (id)initWithScaleFactor:(float)arg1;

@end

