//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface DOCKFolderTileCacheEntry : NSObject
{
    id _layerContents;
    unsigned long long _size;
    BOOL _isPreview;
}

@property(nonatomic) BOOL isPreview; // @synthesize isPreview=_isPreview;
@property(nonatomic) unsigned long long size; // @synthesize size=_size;
@property(retain, nonatomic) id layerContents; // @synthesize layerContents=_layerContents;
- (void).cxx_destruct;
- (id)initWithLayerContents:(id)arg1 size:(unsigned long long)arg2 isPreview:(BOOL)arg3;

@end

