//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DOCKTileEvent.h"

@interface DOCKInternalDropEvent : DOCKTileEvent
{
    struct FloatRect _where;
    unsigned int _oldPosition;
}

- (void)perform:(CDStruct_95d471ab *)arg1;
- (id)initWithTile:(id)arg1 where:(struct FloatRect)arg2 oldPosition:(unsigned int)arg3;

@end

