//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "DOCKGestureHandler.h"
#import "NSXPCConnectionDelegate.h"
#import "NSXPCListenerDelegate.h"

@class NSObject<OS_dispatch_source>, NSString, NSXPCConnection, NSXPCListener;

@interface DockNotificationCenter : NSObject <DOCKGestureHandler, NSXPCListenerDelegate, NSXPCConnectionDelegate>
{
    NSXPCListener *_nclistner;
    NSXPCConnection *_ncConnection;
    NSObject<OS_dispatch_source> *_nc_alive_timer;
    _Bool _isShowing;
    unsigned int _alertWID;
}

@property(readonly, nonatomic) unsigned int alertWID; // @synthesize alertWID=_alertWID;
@property(readonly, nonatomic) _Bool isShowing; // @synthesize isShowing=_isShowing;
- (void).cxx_destruct;
- (void)dockNCOpened:(_Bool)arg1;
- (void)dockRegisterAlertWindow:(unsigned long long)arg1;
- (BOOL)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2;
- (void)_connectionFailed;
- (_Bool)isFluidGesturing;
- (void)fluidGestureEnd:(id)arg1;
- (void)fluidGestureProgress:(id)arg1;
- (_Bool)fluidGestureStart:(id)arg1;
- (void)toggleOnDisplay:(unsigned int)arg1;
- (void)closeIfNecessaryImmediate;
- (void)closeIfNecessaryAndDoWorkAfter:(CDUnknownBlockType)arg1;
- (void)setIsShowing:(_Bool)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

