//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WALayerKitWindow.h"

@class CALayer;

@interface DOCKWindowCopy : WALayerKitWindow
{
    float _height;
    struct CGRect _imageFrame;
    CALayer *_imageLayer;
}

- (void).cxx_destruct;
- (void)setAutohideValue:(float)arg1;
- (id)init;

@end

