//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSObject<OS_dispatch_source>;

@interface DPAdminDesktopExporter : NSObject
{
    NSObject<OS_dispatch_source> *_source;
    unsigned int _widToCapture;
    float _scale;
    _Bool _secondary;
}

- (void).cxx_destruct;
- (void)_export;
- (void)exportWindow:(unsigned int)arg1 scale:(float)arg2;
- (void)dealloc;
- (id)init;

@end

