//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DPPictureInfo.h"

@interface DPDefaultPictureInfo : DPPictureInfo
{
}

- (void)nextImageURL:(CDUnknownBlockType)arg1;
- (id)initWithDisplay:(unsigned int)arg1 realDisplay:(unsigned int)arg2 spaceUUID:(id)arg3 displayUUID:(id)arg4;

@end

