//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CAContext, DPDesktopPicture, NSObject<OS_xpc_object>;

@interface DPRemoteConnection : NSObject
{
    NSObject<OS_xpc_object> *_peer;
    CAContext *_context;
    DPDesktopPicture *_picture;
}

@property(retain, nonatomic) CAContext *context; // @synthesize context=_context;
@property(nonatomic) __weak DPDesktopPicture *picture; // @synthesize picture=_picture;
- (void).cxx_destruct;
- (void)_connectionClosed;
- (void)_handleEvent:(id)arg1;
- (id)description;
- (void)dealloc;
- (id)initWithPeer:(id)arg1;

@end

