//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMapTable;

@interface DPStatementCache : NSObject
{
    NSMapTable *_statements;
}

- (void).cxx_destruct;
- (void)finalize;
- (struct sqlite3_stmt *)statementWithString:(id)arg1 database:(struct sqlite3 *)arg2 result:(int *)arg3;
- (void)dealloc;
- (id)init;

@end

