//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableSet, NSObject<OS_dispatch_queue>;

@interface DPWakeupSource : NSObject
{
    NSMutableSet *_desktopPictures;
    CDUnknownBlockType _callback;
    NSObject<OS_dispatch_queue> *_queue;
    unsigned int _notifier;
    struct IONotificationPort *_powerPort;
    unsigned int _powerSource;
}

- (void).cxx_destruct;
- (void)_powerMessage:(unsigned int)arg1 argument:(void *)arg2;
- (BOOL)removeDesktopPicture:(id)arg1;
- (void)addDesktopPicture:(id)arg1;
- (void)invalidate;
- (void)dealloc;
- (id)initWithDesktopPicture:(id)arg1 callback:(CDUnknownBlockType)arg2;

@end

