//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString;

@protocol ECAccessible <NSObject>
@property(readonly, nonatomic) NSArray *axObservers;
@property(readonly, nonatomic) NSArray *axActionNames;
@property(readonly, nonatomic) NSArray *axAttributeNames;
- (unsigned int)axWindow:(int *)arg1;
- (int)axPerformAction:(NSString *)arg1;
- (NSString *)axActionDescription:(NSString *)arg1 error:(int *)arg2;
- (int)axSetValue:(id)arg1 forKey:(NSString *)arg2;
- (_Bool)axIsAttributeSettable:(NSString *)arg1 error:(int *)arg2;
- (id)axValueForKey:(NSString *)arg1 error:(int *)arg2;
- (NSArray *)axAttributeValues:(NSString *)arg1 index:(unsigned long long)arg2 maxValues:(unsigned long long)arg3 error:(int *)arg4;
- (unsigned long long)axAttributeValueCount:(NSString *)arg1 error:(int *)arg2;
@end

