//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ECModalEventCapture.h"

@interface ECModalEventCaptureDelegate : ECModalEventCapture
{
}

- (BOOL)respondsToAction:(SEL)arg1 delegateAction:(SEL)arg2;
- (BOOL)performAction:(SEL)arg1 delegateAction:(SEL)arg2 withEvent:(id)arg3;

@end

