//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class ECPage, ECPager, NSArray;

@protocol ECPagerSource <NSObject>
- (NSArray *)pageItemsForPager:(ECPager *)arg1;
- (ECPage *)makePageForPager:(ECPager *)arg1 atIndex:(unsigned long long)arg2;
- (unsigned long long)numberOfPagesForPager:(ECPager *)arg1;

@optional
- (void)didChangeToPageIndex:(unsigned long long)arg1;
- (void)willChangeToPageIndex:(unsigned long long)arg1;
- (void)removePage:(ECPage *)arg1 forPager:(ECPager *)arg2;
- (void)addPageForPager:(ECPager *)arg1;
- (void)layoutPage:(ECPage *)arg1 forPager:(ECPager *)arg2;
@end

