//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "ECEventHandling.h"
#import "ECEventHandlingDelegate.h"
#import "ECKeyboardNavigating.h"

@class ECPagerLayer, NSMutableArray, NSString;

@interface ECPager : NSObject <ECEventHandling, ECEventHandlingDelegate, ECKeyboardNavigating>
{
    ECPagerLayer *_layer;
    id <ECPagerSource> _pagerSource;
    NSMutableArray *_pages;
    BOOL _disableScrolling;
}

@property(nonatomic) BOOL disableScrolling; // @synthesize disableScrolling=_disableScrolling;
@property(readonly, nonatomic) NSMutableArray *pages; // @synthesize pages=_pages;
@property(nonatomic) __weak id <ECPagerSource> pagerSource; // @synthesize pagerSource=_pagerSource;
@property(readonly, nonatomic) ECPagerLayer *layer; // @synthesize layer=_layer;
- (void).cxx_destruct;
- (BOOL)navigate:(int)arg1 withEvent:(id)arg2;
- (BOOL)leftMouseDragged:(id)arg1 inLayer:(id)arg2;
- (void)didChangeToPageIndex:(unsigned long long)arg1;
- (void)willChangeToPageIndex:(unsigned long long)arg1;
- (void)invalidate;
- (void)layout;
@property(nonatomic) int pagerControlVisibility; // @dynamic pagerControlVisibility;
@property(readonly, nonatomic) Class pagerLayerClass;
@property(nonatomic) double bottomPageMargin; // @dynamic bottomPageMargin;
@property(nonatomic) double topPageMargin; // @dynamic topPageMargin;
@property(nonatomic) double rightPageMargin; // @dynamic rightPageMargin;
@property(nonatomic) double leftPageMargin; // @dynamic leftPageMargin;
@property(nonatomic) unsigned long long currentPageIndex; // @dynamic currentPageIndex;
- (id)initWithPagerSource:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(nonatomic) unsigned long long selectedIndex;
@property(readonly) Class superclass;

@end

