//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ECSBMoveItemDragState.h"

@class ECSBGroupItem;

@interface ECSBCloseGroupDragState : ECSBMoveItemDragState
{
    ECSBGroupItem *_groupItem;
    _Bool _removeWhenClosed;
}

@property(readonly, nonatomic) ECSBGroupItem *groupItem; // @synthesize groupItem=_groupItem;
@property(nonatomic) _Bool removeWhenClosed; // @synthesize removeWhenClosed=_removeWhenClosed;
- (void).cxx_destruct;
- (void)endTransition;
- (void)beginTransition;
- (int)type;

@end

