//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class ECEvent;

@protocol ECSBActionHandling <NSObject>
- (void)performRemoveActionForItem:(id)arg1 withEvent:(ECEvent *)arg2 sender:(id)arg3;
- (void)performActionForItem:(id)arg1 withEvent:(ECEvent *)arg2 sender:(id)arg3;

@optional
- (BOOL)performDropForItem:(id)arg1 withEvent:(ECEvent *)arg2 sender:(id)arg3;
- (BOOL)canAcceptDropForItem:(id)arg1 withEvent:(ECEvent *)arg2 sender:(id)arg3;
- (void)cancelActionWithEvent:(ECEvent *)arg1 sender:(id)arg2;
@end

