//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ECSBContainerItem.h"

@class ECSBPage;

@interface ECSBPageItem : ECSBContainerItem
{
    ECSBPage *_page;
}

@property(nonatomic) __weak ECSBPage *page; // @synthesize page=_page;
- (void).cxx_destruct;

@end

