//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class ECSizedIconImageCacheRenderObject;

@interface ECSizedIconImageCacheEntry : NSObject
{
    ECSizedIconImageCacheRenderObject *_render;
}

- (void).cxx_destruct;
- (id)replacementObjectForCoder:(id)arg1;
- (void *)CA_copyRenderValue;
- (id)image;
- (unsigned int)height;
- (unsigned int)width;
- (id)description;
- (void)dealloc;
- (id)initWithRenderObject:(id)arg1;

@end

