//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface ECSizedIconImageCache : NSObject
{
}

+ (void)removeEntryForIcon:(struct OpaqueIconRef *)arg1 withSize:(int)arg2 andScaleFactor:(float)arg3;
+ (id)entryWithIcon:(struct OpaqueIconRef *)arg1 forSize:(int)arg2 andScaleFactor:(float)arg3 queue:(id)arg4 completion:(CDUnknownBlockType)arg5;
+ (id)entryWithIcon:(struct OpaqueIconRef *)arg1 forSize:(int)arg2 andScaleFactor:(float)arg3;

@end

