//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CALayer.h"

@class ECRoundBackdropLayer, ECTextLayer;

@interface ECTooltipLayer : CALayer
{
    ECRoundBackdropLayer *_backgroundLayer;
    ECTextLayer *_textLayer;
    float _scaleFactor;
}

@property(readonly, nonatomic) ECTextLayer *textLayer; // @synthesize textLayer=_textLayer;
- (void).cxx_destruct;
- (void)layout;
@property(readonly, nonatomic) struct CGSize preferredSize; // @dynamic preferredSize;
- (id)initWithString:(id)arg1 scaleFactor:(float)arg2 material:(unsigned long long)arg3 rimStyle:(unsigned char)arg4;

@end

