//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "LPAppTreeNode.h"

@class LPItem<LPLayoutItem>, NSArray;

@interface LPAppTreeApp : LPAppTreeNode
{
    LPItem<LPLayoutItem> *_app;
}

+ (id)_pathForApp:(id)arg1;
@property(readonly, nonatomic) LPItem<LPLayoutItem> *app; // @synthesize app=_app;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSArray *pathComponents;
- (BOOL)isLeaf;
- (id)initWithApp:(id)arg1;

@end

