//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSSet;

@interface LPLayoutBlacklist : NSObject
{
    NSSet *_bundleIDBlacklist;
    unsigned long long _version;
    NSArray *_rulesBasedBlacklist;
}

@property unsigned long long version; // @synthesize version=_version;
- (void).cxx_destruct;
- (BOOL)itemBlacklisted:(id)arg1;
- (id)initWithDictionary:(id)arg1;

@end

