//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@protocol LPLayoutItem <NSObject>
@property(readonly, nonatomic) BOOL addedByUser;
@property(readonly, nonatomic) BOOL isStoreApp;
@property(readonly, nonatomic) NSString *blacklistName;
@property(readonly, nonatomic) NSString *bundleIdentifier;
@end

