//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "LPGroup.h"

@interface LPPage : LPGroup
{
}

- (_Bool)isPage;
- (_Bool)isGroup;
- (_Bool)isEmpty;
- (_Bool)pagesOnly;
- (id)initWithItems:(id)arg1;
- (void)updateTitleStorage;
- (int)storageType;

@end

