//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "LPLayout.h"

@interface LPWidgetLayout : LPLayout
{
}

- (BOOL)layoutItemsToNextAvailableSpace:(id)arg1 withOptions:(int)arg2;
- (BOOL)layoutForInitial:(id)arg1;
- (id)layoutKey;

@end

