//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WVSystemSpace.h"

@interface WVDashboardSpace : WVSystemSpace
{
}

- (id)_createSpace:(id)arg1;
- (id)_createUUID;
- (_Bool)isDashboard;
- (id)messageTracerDescription;
- (void)removePid:(int)arg1;
- (void)addPid:(int)arg1;

@end

