//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class WAWindow, _CGSSpace;

@interface WVDragWindow : NSObject
{
    unsigned int _wid;
    struct OpaqueCoreDragHandler *_trackingHandler;
    struct OpaqueCoreDragHandler *_receiveHandler;
    WAWindow *_springWindow;
    _CGSSpace *_space;
}

@property(retain, nonatomic) WAWindow *springWindow; // @synthesize springWindow=_springWindow;
@property(nonatomic) unsigned int wid; // @synthesize wid=_wid;
- (void).cxx_destruct;
- (void)stopTracking;
- (void)dealloc;
- (id)init;

@end

