//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WALayerKitWindow.h"

@class WVExposeHiliteLayer, WVWindowsLayer;

@interface WVExposeHiliteWindow : WALayerKitWindow
{
    WVWindowsLayer *_windowsLayer;
    WVExposeHiliteLayer *_hiliteLayer;
}

@property(readonly, nonatomic) WVExposeHiliteLayer *hiliteLayer; // @synthesize hiliteLayer=_hiliteLayer;
@property(readonly, nonatomic) __weak WVWindowsLayer *windowsLayer; // @synthesize windowsLayer=_windowsLayer;
- (void).cxx_destruct;
- (void)dealloc;
- (id)initWithWindowsLayer:(id)arg1 forDisplay:(unsigned int)arg2;

@end

