//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class ECEvent, WVExposeCluster;

@protocol WVWindowActionHandling <NSObject>
- (BOOL)canExpandCluster:(id)arg1;
- (void)windowAtIndexSelected:(unsigned long long)arg1 sender:(id)arg2;
- (void)performActionOnCluster:(WVExposeCluster *)arg1 withEvent:(ECEvent *)arg2 sender:(id)arg3;
- (void)performWindowActionAtIndex:(unsigned long long)arg1 withEvent:(ECEvent *)arg2 sender:(id)arg3;
@end

