//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CALayer.h"

#import "ECEventHandling.h"
#import "ECEventHandlingDelegate.h"
#import "ECKeyboardNavigating.h"

@class ECTooltipLayer, NSArray, NSMutableArray, NSObject<OS_dispatch_source>, NSString, WALayerKitWindow, WAWindow, WVExposeCellLayer, WVExposeHiliteWindow;

@interface WVWindowsLayer : CALayer <ECEventHandling, ECEventHandlingDelegate, ECKeyboardNavigating>
{
    NSMutableArray *_cellLayers;
    id <WVWindowActionHandling> _handler;
    unsigned long long _selectedIndex;
    WVExposeHiliteWindow *_hiliteWindow;
    unsigned int _rows;
    unsigned int _cols;
    ECTooltipLayer *_hoverLayer;
    WVExposeCellLayer *_expandedCellLayer;
    WVExposeCellLayer *_previewedCell;
    struct CGRect _previewCellOriginalFrame;
    WVExposeCellLayer *_previewCellOriginalNextSibling;
    float _scaleFactor;
    NSObject<OS_dispatch_source> *_springTimer;
    BOOL _shown;
    WALayerKitWindow *_window;
    BOOL _disableSelections;
}

@property(nonatomic) float scaleFactor; // @synthesize scaleFactor=_scaleFactor;
@property(nonatomic) BOOL disableSelections; // @synthesize disableSelections=_disableSelections;
@property(readonly, nonatomic) WALayerKitWindow *window; // @synthesize window=_window;
@property(nonatomic) BOOL shown; // @synthesize shown=_shown;
@property(nonatomic) __weak id <WVWindowActionHandling> handler; // @synthesize handler=_handler;
- (void).cxx_destruct;
- (BOOL)navigate:(int)arg1 withEvent:(id)arg2;
- (BOOL)keyDown:(id)arg1;
- (BOOL)leftMouseDraggedExited:(id)arg1 inLayer:(id)arg2;
- (BOOL)mouseExited:(id)arg1 inLayer:(id)arg2;
- (BOOL)leftMouseDraggedEntered:(id)arg1 inLayer:(id)arg2;
- (BOOL)dragSpring:(id)arg1;
- (BOOL)leftMouseDragged:(id)arg1;
- (BOOL)mouseEntered:(id)arg1 inLayer:(id)arg2;
- (void)_handleMouseEnteredExited:(BOOL)arg1 forLayer:(id)arg2;
- (BOOL)leftMouseUp:(id)arg1 inLayer:(id)arg2;
- (BOOL)leftMouseDown:(id)arg1 inLayer:(id)arg2;
@property(retain, nonatomic) NSArray *windows; // @dynamic windows;
@property(readonly, nonatomic) WAWindow *selectedWindow;
@property(nonatomic) unsigned long long selectedIndex; // @dynamic selectedIndex;
- (void)_updateSelectionWindow;
- (id)cellLayers;
- (void)clearPreviewedWindow;
- (_Bool)setPreviewedWindow:(id)arg1;
- (void)_performWindowActionOnIndex:(unsigned long long)arg1 withEvent:(id)arg2;
- (void)didPerformWindowAction;
- (void)willPerformWindowActionForWindows:(id)arg1;
- (void)updateSelectionBasedOnCurrentMouseLocation;
- (BOOL)canExpandTextOfCellLayer:(id)arg1;
- (id)addWindows:(id)arg1;
- (id)removeWindowsForCID:(unsigned int)arg1;
- (BOOL)useBigWindowSelection;
- (unsigned long long)indexOfWindow:(id)arg1;
- (id)windowAtIndex:(unsigned long long)arg1;
- (void)invalidate;
- (void)_collapseTextOfCellLayer:(id)arg1;
- (void)_removeHoverLayer;
- (void)_expandTextOfCellLayer:(id)arg1;
- (void)dealloc;
- (id)initWithHandler:(id)arg1 window:(id)arg2 forDisplay:(unsigned int)arg3 andScaleFactor:(float)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

