/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <QuartzCore/QuartzCore.h>

@class ECMaterialLayer;

@interface DOCKFloorLayer : CALayer
{
    ECMaterialLayer *_materialLayer;
    CALayer *_separatorLayer;
    CALayer *_glassLayer;
    CGRect _previousFrame;
    int _orientation;
    CGFloat _separatorPosition;
    unsigned int _lastDisplay;
    float _radius;
}

@property(nonatomic) float radius; // @synthesize radius=_radius;
//- (void).cxx_destruct;
- (void)layoutSublayers;
- (void)reduceTransparencyChanged;
- (void)backgroundChanged;
- (void)displayReconfig;
- (void)scaleFactorChanged;
- (void)updateFrame:(CGRect)arg1;
- (void)setGlobalSeparatorPosition:(CGFloat)arg1;
- (void)setOrientation:(int)arg1;
- (id)initWithOrientation:(int)arg1 hasSeparator:(BOOL)arg2;

@end

