/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <QuartzCore/QuartzCore.h>
#import "Tile.h"

@interface DOCKLabelLayer : CALayer
{
    float _blendFrom;
    float _blendNow;
    float _blendTo;
    double _blendST;
    double _blendDur;
    Tile *_source;
    unsigned int _blending:1;
    unsigned int _needUpdate:1;
    CALayer *_backdrop;
}

//- (void).cxx_destruct;
- (void)_updateLabelImage:(float)arg1;
- (void)update;
- (void)reduceTransparencyChanged;
- (void)backgroundChanged;
- (void)scaleFactorChanged;
- (void)detach;
- (void)attach:(id)arg1;
- (id)init;

@end

