/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <QuartzCore/QuartzCore.h>

@class CABackdropLayer, NSString;

@interface ECMaterialLayer : CALayer
{
    CABackdropLayer *_backdropLayer;
    CALayer *_tintLayer;
    NSString *_groupName;
    _Bool _reduceTransparency;
    NSUInteger _material;
}

+ (void)initialize;
@property(nonatomic) _Bool reduceTransparency; // @synthesize reduceTransparency=_reduceTransparency;
@property(nonatomic) unsigned long long material; // @synthesize material=_material;
- (void)_buildLayerTree;
- (void)setBounds:(CGRect)arg1;
@property(nonatomic) float blurRadius;
- (id)initWithMaterial:(NSUInteger)arg1 groupName:(NSString *)arg2 reduceTransparency:(_Bool)arg3;

@end

