#!/bin/bash

# Maintained By	: Wolfgang Baird
# Version		: 4.0
# Updated		: Dec / 30 / 2016

install_app() {
	echo -n ""
	# "$resourceDirectory"/trash "$oldDirectory"
    /usr/bin/osascript -e  "tell application \"Finder\" move POSIX file \"$oldDirectory\" to trash end tell"
	sleep 1
	_oldDIR=$(dirname "$oldDirectory")
	/usr/bin/osascript -e "tell application \"Finder\" to move POSIX file \"$replacementApp\" to POSIX file \"$_oldDIR\" with replacing"
	echo ""
	echo "Process complete"
	sleep 1
	open -a "$oldDirectory"
}


debug() {
	echo "DEBUG: $*" >/dev/null
}

# Directory stuff
scriptDirectory=$(cd "${0%/*}" && echo $PWD)
resourceDirectory=$(dirname "$scriptDirectory")/resource
cocoaDirectory="$resourceDirectory"/cocoaDialog.app/Contents/MacOS/cocoaDialog

tdir="$scriptDirectory"
for i in {1..4}; do
	tdir=$(dirname "$tdir")
done
tdir="$tdir"/Pashua.app/Contents/MacOS/Pashua

# Help
if [[ "$#" = 0 ]]; then
	echo "Usage:"
	echo ""
	echo "\$1 - Check or Install update -- c/i"
	echo "\$2 - path of app"
	echo "\$3 - app bundle ID"
	echo "\$4 - local version"
	echo "\$5 - URL to download current version"
    echo "\$6 - URL to view changelog"
    echo "\$7 - URL to download current version"
    echo "\$8 - Update without prompt -- 0/1"
	echo ""
	echo "END"
fi

# Necessary information
# 1 - Check/Install
# 2 - Directory of local application to be updated
# 3 - Bundle identifier of application
opperation="$1"
oldDirectory="$2"
prefbundle="$3"
applicationName=${oldDirectory##*/}
applicationName=${applicationName%.app}

# redirect output
mkdir -pv ~/Library/Application\ Support/cDock/logs

if [[ $opperation = i ]]; then
	exec &>~/Library/Application\ Support/cDock/logs/legacy_update.log

	for item in "$@"; do
		echo "$item"
	done

	if [[ -e "$oldDirectory" ]]; then
		# Find package
		# /Some.app/Content/Resources/updates/w_updater.app/Content/Resources/script
		replacementApp=$(dirname "$scriptDirectory")
		for i in {1..5}; do
			replacementApp=$(dirname "$replacementApp")
		done
		echo "new app -- $replacementApp"
		echo "old app -- $oldDirectory"
		echo "Closing and Installing app"
        echo "${applicationName}"
        #for item in $(ps aux | grep [c]Dock | tr -s ' ' | cut -d ' ' -f 2); do kill "$item"; done
        killall "cDock"
        killall "cDock 2"
        killall "${applicationName}"
		killall "CocoaDialog"
		killall "cocoaDialog"
		killall "Pashua"
		sleep 1
		install_app
	else
		echo "No such application \"$2\" exists"
	fi
fi

# END
