//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ECTooltipLayer.h"

@class DOCKStackExpandedItemLayer;

@interface _DOCKStackGridHoverLayer : ECTooltipLayer
{
    DOCKStackExpandedItemLayer *_expandedItemLayer;
}

@property(nonatomic) __weak DOCKStackExpandedItemLayer *expandedItemLayer; // @synthesize expandedItemLayer=_expandedItemLayer;
- (void).cxx_destruct;
- (id)hitTest:(struct CGPoint)arg1;

@end

