//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface ASDragInfo : NSObject
{
    _Bool _canAccept;
    _Bool _validFSRef;
    struct FSRef _fsref;
}

@property(readonly, nonatomic) _Bool canAccept; // @synthesize canAccept=_canAccept;
@property(readonly, nonatomic) const struct FSRef *fsref; // @dynamic fsref;
- (id)initWithDrag:(struct OpaqueCoreDrag *)arg1 forASN:(id)arg2;

@end

