//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class DBWidget;

@interface DBRippleInfo : NSObject
{
    unsigned int _cid;
    unsigned int _dropWindow;
    unsigned int _rippleWindow;
    unsigned int _filter;
    struct CGRect _bounds;
    DBWidget *_widget;
    CDUnknownFunctionPointerType _callback;
    _Bool _slow;
}

- (void).cxx_destruct;
- (void)run;
- (void)dealloc;
- (id)initWithConnection:(unsigned int)arg1 cornerRadius:(float)arg2 dropWindow:(unsigned int)arg3 bounds:(struct CGRect)arg4 slow:(_Bool)arg5 widget:(id)arg6 callback:(CDUnknownFunctionPointerType)arg7;

@end

