//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CALayer.h"

#import "ECEventHandling.h"

@class NSString;

@interface DOCKStackGoBackButtonLayer : CALayer <ECEventHandling>
{
    CALayer *_imageLayer;
    unsigned int _highlighted:1;
    unsigned int _trackingMouseDown:1;
    CDUnknownBlockType _block;
}

@property(nonatomic) _Bool highlighted; // @synthesize highlighted=_highlighted;
@property(copy, nonatomic) CDUnknownBlockType block; // @synthesize block=_block;
- (void).cxx_destruct;
- (BOOL)leftMouseDraggedExited:(id)arg1;
- (BOOL)leftMouseDraggedEntered:(id)arg1;
- (BOOL)leftMouseDragged:(id)arg1;
- (BOOL)leftMouseUp:(id)arg1;
- (BOOL)leftMouseDown:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

