//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CALayer.h"

@interface DOCKProgressLayer : CALayer
{
    CALayer *_rimLayer;
    CALayer *_fillLayer;
    float _progress;
}

@property(nonatomic) float progress; // @synthesize progress=_progress;
- (void).cxx_destruct;
- (void)dockBackgroundChanged;
- (void)layoutSublayers;
- (id)init;

@end

