//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class ECEvent;

@protocol ECKeyboardNavigating <NSObject>
- (BOOL)navigate:(int)arg1 withEvent:(ECEvent *)arg2;

@optional
@property(nonatomic) unsigned long long selectedIndex;
@end

