//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CALayer, WALayerKitWindow;

@interface ECModalEventCapture : NSObject
{
    id _handler;
    CALayer *_layer;
    int _eventType;
    WALayerKitWindow *_window;
}

+ (id)modalEventCaptureWithHandler:(id)arg1 layer:(id)arg2 eventType:(int)arg3;
@property(nonatomic) WALayerKitWindow *window; // @synthesize window=_window;
@property(readonly, nonatomic) int eventType; // @synthesize eventType=_eventType;
@property(retain, nonatomic) CALayer *layer; // @synthesize layer=_layer;
- (void).cxx_destruct;
- (BOOL)respondsToAction:(SEL)arg1 delegateAction:(SEL)arg2;
- (BOOL)performAction:(SEL)arg1 delegateAction:(SEL)arg2 withEvent:(id)arg3;
- (id)description;
- (id)initWithHandler:(id)arg1 layer:(id)arg2 eventType:(int)arg3;

@end

