//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CALayer;

@protocol ECModalEventHandler <NSObject>
@property(readonly, nonatomic) CALayer *modalEventLayer;
- (BOOL)handlesModalDragEvents;

@optional
- (struct CGRect)convertRectToGlobal:(struct CGRect)arg1;
- (struct CGPoint)convertPointFromGlobal:(struct CGPoint)arg1;
- (void)modalEventProcessed;
@end

