//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSString;

@protocol ECSBDataSource <NSObject>
- (void)setValue:(id)arg1 forKey:(NSString *)arg2 ofItem:(id)arg3;
- (id)valueForKey:(NSString *)arg1 ofItem:(id)arg2 withInfo:(NSDictionary *)arg3;
@end

