//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@protocol ECSBGridPagerSourceClient <NSObject>
- (void)setGridValue:(id)arg1 forKey:(NSString *)arg2 atIndex:(unsigned long long)arg3 forPageAtIndex:(unsigned long long)arg4;
- (void)gridDataSourceInvalidatedAtRange:(struct _NSRange)arg1 forPageAtIndex:(unsigned long long)arg2;
- (void)gridDataSourceInvalidatedForPageAtIndex:(unsigned long long)arg1;
@end

