//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class ECSBItem, ECSBPageItem;

@interface ECSBOverflowItem : NSObject
{
    ECSBItem *_item;
    ECSBPageItem *_pageItem;
}

@property(readonly, nonatomic) ECSBPageItem *pageItem; // @synthesize pageItem=_pageItem;
@property(readonly, nonatomic) ECSBItem *item; // @synthesize item=_item;
- (void).cxx_destruct;
- (id)initWithItem:(id)arg1 onPageItem:(id)arg2;

@end

