//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@protocol ECSBDataSourceClient <NSObject>
- (struct CGRect)globalBoundsOfIconForItem:(id)arg1;
- (void)confirmRemoveItem:(id)arg1;
- (void)replaceItem:(id)arg1 withItem:(id)arg2 refetchingContents:(BOOL)arg3;
- (void)removeItem:(id)arg1 animating:(BOOL)arg2;
- (void)insertItem:(id)arg1 atIndex:(unsigned long long)arg2 ofParentItem:(id)arg3;
- (void)addItem:(id)arg1 toParentItem:(id)arg2;
- (void)setValue:(id)arg1 forKey:(NSString *)arg2 ofItem:(id)arg3;
@end

