//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@protocol ECScrollbarHandler <NSObject>
- (void)endDragScroll:(id)arg1;
- (void)scrollToValue:(double)arg1 sender:(id)arg2;
- (void)beginDragScroll:(id)arg1;
- (void)scrollDownPage:(id)arg1;
- (void)scrollUpPage:(id)arg1;
- (void)scrollDown:(id)arg1;
- (void)scrollUp:(id)arg1;
@end

