//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FSWMContainer.h"

@interface FSWMRootContainer : FSWMContainer
{
    unsigned int _did;
    unsigned long long _spid;
}

@property(readonly, nonatomic) unsigned int did; // @synthesize did=_did;
@property(readonly, nonatomic) unsigned long long spid; // @synthesize spid=_spid;
- (id)initWithSpace:(unsigned long long)arg1 andDisplay:(unsigned int)arg2;

@end

