//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface WATransactionHook : NSObject
{
    void *_transaction;
}

@property(nonatomic) void *transaction; // @synthesize transaction=_transaction;
- (void)dealloc;
- (id)initWithTransaction:(void *)arg1;

@end

